### ISSUE TITLE
Replace read_sample with read_samples

### ISSUE THREAD

**Issue by sdl1** [ScottishCovidResponse/SimulationData.jl#16]
See here: https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/640

**Comment by sdl1** [comment]
I think this requires data_pipeline_api to release `0.7.0`

**Comment by AlexRobson** [comment]
I'm unsure what the correct behaviour for these tests should be now: 

```
            #@test read_samples(api, "parameter-read", "example-estimate") == 1.0
            #@test read_samples(api, "parameter-read", "example-distribution") isa Real
            #@test read_samples(api, "parameter-read", "example-samples") ∈ [1, 2, 3]
```

They are throwing a ValueError in Python (by design). 

https://github.com/ScottishCovidResponse/SimulationData.jl/pull/20

I think they essentially need to be deleted. Ideally, we would have a test for a Python ValueError, but this is going the route of testing the package that you are using, now the tests of the package you are developing.

**Comment by sdl1** [comment]
Yeah I think we probably can just test
```
read_samples(api, "parameter-read", "example-samples") == [1, 2, 3]
```
(that should pass) and delete the others

**Comment by AlexRobson** [comment]
This should have closed with https://github.com/ScottishCovidResponse/SimulationData.jl/pull/20
